@extends('admin_layout.app')
@section('title','Tableau de bord — IPCS CODIR APP')
@section('admin')
<div class="codir-page-head"><div><div class="codir-eyebrow">Vue d'ensemble</div><h1>Bonjour {{ Auth::user()->prenoms ?? Auth::user()->nom ?? 'à vous' }} 👋</h1><p>Voici l'état actuel de l'activité et des décisions d'IPCS.</p></div><div class="codir-actions"><a href="{{ route('reunions.create') }}" class="btn btn-primary"><i class="fa fa-plus mr-1"></i> Nouvelle réunion</a><a href="{{ route('rapports.codir.index') }}" class="btn btn-light"><i class="fa fa-bar-chart mr-1"></i> Voir le rapport</a></div></div>
<div class="row mb-3">
@foreach([['usersCount','Utilisateurs','fa-users'],['reunionsCount','Réunions','fa-calendar'],['activitesCount','Activités','fa-briefcase'],['tachesCount','Tâches','fa-check-square-o']] as $k)
<div class="col-xl-3 col-md-6"><div class="codir-kpi"><div class="codir-kpi-icon"><i class="fa {{ $k[2] }}"></i></div><p class="codir-kpi-value">{{ ${$k[0]} }}</p><div class="codir-kpi-label">{{ $k[1] }}</div></div></div>
@endforeach
</div>
<div class="row mb-3"><div class="col-12"><div class="codir-card"><div class="card-block"><div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="mb-1">État des actions</h5><small class="text-muted">Répartition des tâches par statut</small></div><a href="{{ route('taches.index') }}" class="btn btn-light">Toutes les tâches</a></div><div class="row"><div class="col-md-3"><div class="codir-kpi"><p class="codir-kpi-value">{{ $tachesAFaire }}</p><div class="codir-kpi-label">À faire</div></div></div><div class="col-md-3"><div class="codir-kpi"><p class="codir-kpi-value">{{ $tachesEnCours }}</p><div class="codir-kpi-label">En cours</div></div></div><div class="col-md-3"><div class="codir-kpi"><p class="codir-kpi-value">{{ $tachesTerminees }}</p><div class="codir-kpi-label">Terminées</div></div></div><div class="col-md-3"><div class="codir-kpi"><p class="codir-kpi-value">{{ $tachesEnRetard }}</p><div class="codir-kpi-label">En retard</div></div></div></div></div></div></div></div>
<div class="row"><div class="col-xl-6 mb-3"><div class="card h-100"><div class="card-header d-flex justify-content-between align-items-center"><h5>Dernières réunions</h5><a href="{{ route('reunions.index') }}" class="btn btn-light">Voir tout</a></div><div class="card-block p-0"><div class="table-responsive"><table class="table"><thead><tr><th>Réunion</th><th>Date</th><th>Lieu</th><th>Actions</th></tr></thead><tbody>@forelse($lastReunions as $reunion)<tr><td><strong>{{ $reunion->titre }}</strong></td><td>{{ optional($reunion->date)->format('d/m/Y') ?? $reunion->date }}</td><td>{{ $reunion->lieu }}</td><td><span class="badge badge-info">{{ $reunion->taches->count() }} tâches</span></td></tr>@empty<tr><td colspan="4" class="codir-empty">Aucune réunion récente.</td></tr>@endforelse</tbody></table></div></div></div></div>
<div class="col-xl-6 mb-3"><div class="card h-100"><div class="card-header d-flex justify-content-between align-items-center"><h5>Dernières tâches</h5><a href="{{ route('taches.index') }}" class="btn btn-light">Voir tout</a></div><div class="card-block p-0"><div class="table-responsive"><table class="table"><thead><tr><th>Tâche</th><th>Statut</th><th>Responsables</th></tr></thead><tbody>@forelse($lastTaches as $tache)<tr><td><strong>{{ $tache->titre }}</strong></td><td><span class="badge badge-primary">{{ $tache->statut }}</span></td><td>@forelse($tache->users as $user)<span class="badge badge-info mr-1">{{ $user->nom }}</span>@empty<span class="text-muted">Non affectée</span>@endforelse</td></tr>@empty<tr><td colspan="3" class="codir-empty">Aucune tâche récente.</td></tr>@endforelse</tbody></table></div></div></div></div></div>
@endsection
